You are helping write a resume. Based on the information given below, write a short item that could be used in the "experience" section.

The company name is {company_name}

I worked on this project: {period}

Some technologies used were {technologies_used}

Other information: {other_information}

An example input:

The company name is Hubble

I worked on this project: may 2022 until the end of 2023

Some technologies used were Kotlin, Spring, Google Cloud

Other information: extract data, export to hubble

An example output:

Hubble (may 2022 - december 2023)
Kotlin, Spring, Google Cloud

Created an application using Google Cloud to extract data, transform it and export it to Hubble's systems.